<template lang="pug">
  div(class='aboutme')
    p(class='info') the quick brown fox jumps over the lazy dog. the quick brown fox jumps over the lazy dog. the quick brown fox jumps over the lazy dog. the quick brown fox jumps over the lazy dog.

</template>

<script>
export default {

};
</script>

<style lang="scss">
  .aboutme {
    display: flex;
    text-align: center;
    border-style: solid;
    border-color: orange;
    .info {
      display: block;
      flex: 1;
    }
  }
</style>


